### ISSUE TITLE
[Bug]: Nature's Aura manual is nonfunctional

### ISSUE THREAD

**Issue by tyreforhyred** [Y-Xiao233/Compact-World-Expert#20]
### Modpack Version

Beta v1.4.0 

### Describe your issue

![image](https://github.com/Y-Xiao233/Compact-World-Expert/assets/76914208/b9dbf01d-0187-498d-bef2-8297cd57a846)
due to this error the Nature's Aura manual is nonfunctional, this makes Ritual of the Forest setup confusing without looking up external documentation on how it should be spaced.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Y-Xiao233** [comment]
![cdf61542-a928-423b-a7cf-f831de57091e](https://github.com/Y-Xiao233/Compact-World-Expert/assets/159413429/7a644312-6c05-4837-a444-4369734bac8a)
I did not encounter this issue in Beta v1.4.0. Please send the log file to let me know more information

**Comment by Marsshiii** [comment]
Caused by: java.lang.RuntimeException: Error while loading entry naturesaura:using/animal_spawner page 5
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:249) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	... 33 more
Caused by: java.lang.RuntimeException: Unknown entity id: 
	at vazkii.patchouli.common.util.EntityUtil.loadEntity(EntityUtil.java:48) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.component.ComponentEntity.build(ComponentEntity.java:40) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.template.BookTemplate.lambda$build$0(BookTemplate.java:122) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at vazkii.patchouli.client.book.template.BookTemplate.build(BookTemplate.java:122) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:29) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:246) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.19.2-77.jar%23507!/:1.19.2-77]
	... 33 more
 

Here are the logs cause I have the same issue

**Comment by Y-Xiao233** [comment]
I deleted the recipe for summoning entities using the Altar of Birthing, and the recipe in the book was displayed by reading these recipes, which caused a breakdown.

In the next version, I will restore these formulas, but I don't want to see players perform these crafting, so as an alternative, I will delete the Altar of Birthing.

**Comment by Y-Xiao233** [comment]
Beta v1.7.0 fix
